name: Nightly build Ubuntu

on: [push]

jobs:
  

  datconverter_and_compile_pak192-comic-addons:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: install_dependencies
      run: |
          sudo apt-get -y update
          sudo apt-get -ym install libpng-dev
          sudo apt-get -ym install libsdl2-dev
          sudo apt-get -ym install libbz2-dev
          sudo apt-get -ym install autoconf
          svn checkout svn://servers.simutrans.org/simutrans simutrans
    - name: setup
      run: |
        cd simutrans/trunk
        autoconf
        ./configure
        cat config.default >>/dev/stderr
    - name: make makeobj
      run: |
          cd simutrans/trunk/src/makeobj
          make
          mv makeobj ../../../..
          cd ../../..
          rm -rf simutrans


    - name: Compile pak192.comic themes
      run: bash COMPILE_THEME.sh

    - name: Version the Pakset
      run: sed -i "s/copyright=.*/copyright=Pak192.Comic Nightly Rev $(git rev-list --count --first-parent HEAD)/" ./pakset/landscape/ground/outside.dat

    - name: Converting dat files
      run: bash DatConverter.sh -f -a

    - name: Compile pak192.comic addons
      run: bash Compile_Converted_AddOn.sh

    - name: zip converted_addons
      run: |
        mv compiled_converted_addons pak192.comic-nightly-addons-datconverter
        zip -r pak192-nightly-addons-datconverter.zip pak192.comic-nightly-addons-datconverter

    - name: make pak192
      run: |
        bash Compile_Converted.sh

    - name: Rename result
      run: |
        mv compiled_converted pak192.comic-nightly-datconverter
        zip -r pak192-nightly-datconverter.zip pak192.comic-nightly-datconverter

    - name: Update Addons of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./pak192-nightly-addons-datconverter.zip
        asset_name: pak192-nightly-addons-datconverter.zip
        tag: Nightly
        overwrite: true

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./pak192-nightly-datconverter.zip
        asset_name: pak192-nightly-datconverter.zip
        tag: Nightly
        overwrite: true

        
    - name: Update Themes of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./themes.zip
        asset_name: themes.zip
        tag: Nightly
        overwrite: true

  compile_pak192-comic_serverset:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: install_dependencies
      run: |
          sudo apt-get -y update
          sudo apt-get -ym install libpng-dev
          sudo apt-get -ym install libsdl2-dev
          sudo apt-get -ym install libbz2-dev
          sudo apt-get -ym install autoconf
          svn checkout svn://servers.simutrans.org/simutrans simutrans
    - name: setup
      run: |
        cd simutrans/trunk
        autoconf
        ./configure
        cat config.default >>/dev/stderr
    - name: make makeobj
      run: |
          cd simutrans/trunk/src/makeobj
          make
          mv makeobj ../../../..
          cd ../../..
          rm -rf simutrans

    - name: Version the Pakset
      run: sed -i "s/copyright=.*/copyright=Pak192.Comic Severset Rev $(git rev-list --count --first-parent HEAD)/" ./pakset/landscape/ground/outside.dat
    
    - name: Converting dat files
      run: bash DatConverter.sh -f -a

    - name: Compile pak192.comic with extra addons
      run: bash Compile_Converted_Serverset.sh

    - name: zip converted_addons
      run: |
        mv compiled_serverset pak192.comic-serverset-nightly
        zip -r pak192.comic-serverset-nightly.zip pak192.comic-serverset-nightly

    - name: Update Serverset of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./pak192.comic-serverset-nightly.zip
        asset_name: pak192.comic-serverset-nightly.zip
        tag: Nightly
        overwrite: true
        
        
  compile_vehicle_exports:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: install_dependencies
      run: |
          sudo apt-get -y update
          sudo apt-get -ym install libpng-dev
          sudo apt-get -ym install libsdl2-dev
          sudo apt-get -ym install libbz2-dev
          sudo apt-get -ym install autoconf
          sudo apt-get -ym install imagemagick
          svn checkout svn://servers.simutrans.org/simutrans simutrans
    - name: setup
      run: |
        cd simutrans/trunk
        autoconf
        ./configure
        cat config.default >>/dev/stderr
    - name: make makeobj
      run: |
          cd simutrans/trunk/src/makeobj
          make
          mv makeobj ../../../..
          cd ../../..
          rm -rf simutrans

    - name: Compile pak192.comic vehicles als pak128.britain vehicles
      run: bash vehicles-for-export/Compile_Pak128Britain_Vehicles.sh

    - name: zip vehicles
      run: |
        mv Pak128Britain pak192.comic-vehicles-for-pak128britain
        zip -r pak192.comic-vehicles-for-pak128britain.zip pak192.comic-vehicles-for-pak128britain

    - name: Update Serverset of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./pak192.comic-vehicles-for-pak128britain.zip
        asset_name: pak192.comic-vehicles-for-pak128britain.zip
        tag: Nightly
        overwrite: true