name: Nightly build Ubuntu

on: [push]

jobs:
  compile_pak192-comic:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v1

    - name: install_dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -ym install libpng-dev
        sudo apt-get -ym install libsdl2-dev
        sudo apt-get -ym install libbz2-dev
        sudo apt-get -ym install autoconf
        git clone https://github.com/jamespetts/simutrans-extended.git simutrans-extended
    - name: setup
      run: |
        cd simutrans-extended
        autoconf
        ./configure
        cat config.default >>/dev/stderr
    - name: make makeobj
      run: |
          cd simutrans-extended/makeobj
          make
          mv makeobj-extended ../../..
          cd ../../..
          rm -rf simutrans
          
    - name: Converting dat files
      run: bash DatConverter.sh -f -a
      
    - name: make pak192
      run: |
        bash Compile_Converted.sh
    - name: Rename result
      run: |
        mv compiled_converted pak192.comic-extended-nightly
        zip -r pak192.comic-extended-nightly.zip pak192.comic-extended-nightly
    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./pak192.comic-extended-nightly.zip
        asset_name: pak192.comic-extended-nightly.zip
        tag: Nightly
        overwrite: true
        
    - name: make pak192-addons
      run: |
        bash Compile_Converted_AddOn.sh
    - name: Rename result
      run: |
        mv converted_addons pak192.comic-addons-extended-nightly
        zip -r pak192.comic-addons-extended-nightly.zip pak192.comic-addons-extended-nightly
    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./pak192.comic-addons-extended-nightly.zip
        asset_name: pak192.comic-addons-extended-nightly.zip
        tag: Nightly
        overwrite: true
        
        
    - name: make pak192-serverset
      run: |
        bash Compile_Converted_Serverset.sh
    - name: Rename result
      run: |
        mv compiled_serverset pak192.comic-serverset-extended-nightly
        zip -r pak192.comic-serverset-extended-nightly.zip pak192.comic-serverset-extended-nightly
    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./pak192.comic-serverset-extended-nightly.zip
        asset_name: pak192.comic-serverset-extended-nightly.zip
        tag: Nightly
        overwrite: true
        
        