name: Nightly build Ubuntu

on: [push]

jobs:
  compile_pak192-comic:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v1

    - name: install_dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -ym install libpng-dev
        sudo apt-get -ym install libsdl2-dev
        sudo apt-get -ym install libbz2-dev
        sudo apt-get -ym install autoconf
        svn checkout svn://servers.simutrans.org/simutrans simutrans
    - name: setup
      run: |
        cd simutrans/trunk
        autoconf
        ./configure
        cat config.default >>/dev/stderr
    - name: make makeobj
      run: |
          cd simutrans/trunk/makeobj
          make
          mv makeobj ../../..
          cd ../../..
          rm -rf simutrans

    - name: make pak192
      run: |
        bash COMPILE.sh
    - name: Rename result
      run: |
        mv compiled pak192.comic-nightly
        zip -r pak192-nightly.zip pak192.comic-nightly

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./pak192-nightly.zip
        asset_name: pak192-nightly.zip
        tag: Nightly
        overwrite: true

  compile_pak192-comic-addons:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: install_dependencies
      run: |
          sudo apt-get -y update
          sudo apt-get -ym install libpng-dev
          sudo apt-get -ym install libsdl2-dev
          sudo apt-get -ym install libbz2-dev
          sudo apt-get -ym install autoconf
          svn checkout svn://servers.simutrans.org/simutrans simutrans
    - name: setup
      run: |
        cd simutrans/trunk
        autoconf
        ./configure
        cat config.default >>/dev/stderr
    - name: make makeobj
      run: |
          cd simutrans/trunk/makeobj
          make
          mv makeobj ../../..
          cd ../../..
          rm -rf simutrans

    - name: Compile pak192.comic addons
      run: bash COMPILE_ADDON.sh

    - name: zip addons
      run: |
        mv compiled_addons pak192.comic-nightly-addons
        zip -r pak192-nightly-addons.zip pak192.comic-nightly-addons
        
    - name: Compile pak192.comic themes
      run: bash COMPILE_THEME.sh

    - name: Update Addons of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./pak192-nightly-addons.zip
        asset_name: pak192-nightly-addons.zip
        tag: Nightly
        overwrite: true
        
    - name: Update Themes of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./themes.zip
        asset_name: themes.zip
        tag: Nightly
        overwrite: true

  datconverter_and_compile_pak192-comic-addons:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: install_dependencies
      run: |
          sudo apt-get -y update
          sudo apt-get -ym install libpng-dev
          sudo apt-get -ym install libsdl2-dev
          sudo apt-get -ym install libbz2-dev
          sudo apt-get -ym install autoconf
          svn checkout svn://servers.simutrans.org/simutrans simutrans
    - name: setup
      run: |
        cd simutrans/trunk
        autoconf
        ./configure
        cat config.default >>/dev/stderr
    - name: make makeobj
      run: |
          cd simutrans/trunk/makeobj
          make
          mv makeobj ../../..
          cd ../../..
          rm -rf simutrans

    - name: Converting dat files
      run: bash DatConverter.sh -f

    - name: Compile pak192.comic addons
      run: bash Compile_Converted_AddOn.sh

    - name: zip converted_addons
      run: |
        mv compiled_converted_addons pak192.comic-nightly-addons-datconverter
        zip -r pak192-nightly-addons-datconverter.zip pak192.comic-nightly-addons-datconverter

    - name: make pak192
      run: |
        bash Compile_Converted.sh

    - name: Rename result
      run: |
        mv compiled_converted pak192.comic-nightly-datconverter
        zip -r pak192-nightly-datconverter.zip pak192.comic-nightly-datconverter

    - name: Update Addons of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./pak192-nightly-addons-datconverter.zip
        asset_name: pak192-nightly-addons-datconverter.zip
        tag: Nightly
        overwrite: true

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./pak192-nightly-datconverter.zip
        asset_name: pak192-nightly-datconverter.zip
        tag: Nightly
        overwrite: true
        
